export const songdata = [
  {
    id: 1,
    artist: "Rihanna",
    title: "Disturbia",
    key: 10,
    bpm: 123,
  },
  {
    id: 2,
    artist: "Travis Scott",
    title: "Goosebumps",
    key: 9,
    bpm: 123,
  },
  /*{
    id: 3,
    artist: "Pop Smoke",
    title: "For the Night",
    key: 12,
    bpm: 123,
  },*/
  {
    id: 4,
    artist: "Carly Rae Jepsen",
    title: "Call Me Maybe",
    key: 8,
    bpm: 123,
  },
  {
    id: 5,
    artist: "Flo Rida",
    title: "I Dont Like It I Love It",
    key: 6,
    bpm: 123,
  },
  {
    id: 6,
    artist: "Dua Lipa",
    title: "Dont Start Now",
    key: 10,
    bpm: 123,
  },
  {
    id: 7,
    artist: "Madonna",
    title: "Get Into the Groove",
    key: 5,
    bpm: 123,
  },
  /*{
    id: 8,
    artist: "The Weeknd",
    title: "Take My Breath Away",
    key: 5,
    bpm: 123,
  },*/
  {
    id: 9,
    artist: "Rihanna",
    title: "Dont Stop the Music",
    key: 11,
    bpm: 123,
  },
  {
    id: 10,
    artist: "LMFAO",
    title: "Party Rock Anthem",
    key: 4,
    bpm: 123,
  },
  {
    id: 11,
    artist: "David Guetta",
    title: "Im Good",
    key: 6,
    bpm: 123,
  },
  {
    id: 12,
    artist: "Elton John",
    title: "Hold Me Closer",
    key: 8,
    bpm: 123,
  },
  {
    id: 13,
    artist: "Outkast",
    title: "The Way You Move",
    key: 5,
    bpm: 123,
    acapellaOnly: true,
  },
  {
    id: 14,
    artist: "Katy Perry",
    title: "TGIF",
    key:1,
    bpm: 123,
  },
  {
    id: 15,
    artist: "Ylvis",
    title: "What the Fox",
    key: 12,
    bpm: 123,
  },
  {
    id: 16,
    artist: "Maroon 5",
    title: "Moves Like Jagger",
    key: 10,
    bpm: 123,
  },
  {
    id: 17,
    artist: "Black Eyed Peas",
    title: "Feels Like A Good Night",
    key: 9,
    bpm: 123,
  },
  {
    id: 18,
    artist: "DNCE",
    title: "Cake by the Ocean",
    key: 9,
    bpm: 123,
  },
  {
    id: 19,
    artist: "St John",
    title: "Roses Imanbek Remix",
    key: 4,
    bpm: 123,
  },
  {
    id: 20,
    artist: "Becky Hill",
    title: "My Heart Goes La Di Da",
    key: 4,
    bpm: 123,
    instrumentalOnly: true
  },
  {
    id: 21,
    artist: "Shouse",
    title: "Love Tonight",
    key: 4,
    bpm: 123,
    instrumentalOnly: true
  },
  {
    id: 22,
    artist: "Joel Corry",
    title: "OUT OUT",
    key: 1,
    bpm: 123,
  },
  {
    id: 23,
    artist: "Katy Perry",
    title: "Firework",
    key: 4,
    bpm: 123,
  },
  {
    id: 24,
    artist: "Sean Paul",
    title: "Temperature",
    key: 6,
    bpm: 123,
  },
  {
    id: 25,
    artist: "Wolfgang Gartner",
    title: "Forever",
    key: 1,
    bpm: 123,
  },
  {
    id: 26,
    artist: "Kylie Minogue",
    title: "Cant Get You Out of my Head",
    key: 7,
    bpm: 123,
  },
  {
    id: 27,
    artist: "Ed Sheeran",
    title: "Bad Habits",
    key: 10,
    bpm: 123,
  },
  {
    id: 28,
    artist: "Katy Perry",
    title: "California Gurlz",
    key: 7,
    bpm: 123,
  },
  {
    id: 29,
    artist: "Owl City",
    title: "Its Always a Good Time",
    key: 5,
    bpm: 123,
  },
  {
    id: 30,
    artist: "Black Eyed Peas",
    title: "Boom Boom Pow",
    key: 8,
    bpm: 123,
  },
  {
    id: 31,
    artist: "Black Eyed Peas",
    title: "My Humps Lil Jon Remix",
    key: 12,
    bpm: 123,
  },
  {
    id: 32,
    artist: "The Weeknd",
    title: "Moth to a Flame",
    key: 5,
    bpm: 123,
  },
  {
    id: 33,
    artist: "Rednex",
    title: "Cotton Eyed Joe",
    key: 9,
    bpm: 123,
  },
  {
    id: 34,
    artist: "Miley Cyrus",
    title: "Party In the USA",
    key: 2,
    bpm: 123,
  },
  /*{
    id: 35,
    artist: "Dua Lipa",
    title: "Dance the Night",
    key: 5,
    bpm: 123,
  }*/
  {
    id: 36,
    artist: "Billie Eilish",
    title: "LUNCH",
    key: 10,
    bpm: 123,
  },
  {
    id: 37,
    artist: "Whitney Houston",
    title: "How Will I Know Clean Bandit Remix",
    key: 2,
    bpm: 123,
  },
]
