export const songdata = [
  {
    id: 1,
    artist: "Rihanna",
    title: "Disturbia",
    key: 2,
    bpm: 123,
  },
  {
    id: 2,
    artist: "Travis Scott",
    title: "Goosebumps",
    key: 2,
    bpm: 123,
  },
  {
    id: 3,
    artist: "Pop Smoke",
    title: "For the Night",
    key: 2,
    bpm: 123,
  },
  {
    id: 4,
    artist: "Carly Rae Jepsen",
    title: "Call Me Maybe",
    key: 2,
    bpm: 123,
  },
  {
    id: 5,
    artist: "Flo Rida",
    title: "I Dont Like It I Love It",
    key: 2,
    bpm: 123,
  },
  {
    id: 6,
    artist: "Dua Lipa",
    title: "Dont Start Now",
    key: 2,
    bpm: 123,
  },
  {
    id: 7,
    artist: "Madonna",
    title: "Get Into the Groove",
    key: 2,
    bpm: 123,
  },
  {
    id: 8,
    artist: "The Weeknd",
    title: "Take My Breath Away",
    key: 2,
    bpm: 123,
  },
  {
    id: 9,
    artist: "Rihanna",
    title: "Dont Stop the Music",
    key: 2,
    bpm: 123,
  },
  {
    id: 10,
    artist: "LMFAO",
    title: "Party Rock Anthem",
    key: 2,
    bpm: 123,
  },
  {
    id: 11,
    artist: "David Guetta",
    title: "Im Good",
    key: 2,
    bpm: 123,
  },
  {
    id: 12,
    artist: "Elton John",
    title: "Hold Me Closer",
    key: 2,
    bpm: 123,
  },
  {
    id: 13,
    artist: "Outkast",
    title: "The Way You Move",
    key: 2,
    bpm: 123,
  },
  {
    id: 14,
    artist: "Katy Perry",
    title: "TGIF",
    key: 2,
    bpm: 123,
  },
  {
    id: 15,
    artist: "Ylvis",
    title: "What the Fox",
    key: 2,
    bpm: 123,
  }
];
